spring.application.name=backend

# Conexion con PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/homefinder
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}